### PR TITLE
Add arrays to tiny bang

### PR DESCRIPTION
**Pull request by maz**
Arrays are finally finished (~~except for pattern matching on them~~)! Pattern matching works now, too!

@zepalmer @leafac

### CODE REVIEW

**Comment by leafac** [comment]
I don't claim to be a big expert on the subtleties of the theory behind this implementation, but as far as I can tell, this looks great :shipit:

**Comment by maz** [comment]
@zepalmer any feedback?

**Comment by zepalmer** [comment]
This looks quite nice.  My only request is that we have a few more unit tests.  For instance, it'd be good to create a zero length array just to make sure it doesn't wreck something.  It'd be good to verify that we can create two different arrays and that updates to one do not affect the values (or types) of the other.  Finally, it'd be good to create arrays in a loop (via recursion, of course) and then update one of the arrays with a different type to witness the weakness of the type system.  Pseudocode for that last one would be something like

```
let rec f n a =
  a[n] = newArray 5 0 # five zeroes, right?
  if n > 0:
    f (n-1) a
in
let null = `Null () in
let arrayArray = newArray 4 null in
f 4 arrayArray;
a0 = arrayGet arrayArray 0
a1 = arrayGet arrayArray 1
case a0 of
  `Null _ -> ()
  array as a0a ->
    (arraySet a0a 0 null;
    case a1 of
      `Null _ -> ()
      array as a1a ->
        ((arrayGet a1a 0) + 1) # we should expect a type error here
    )
```

To be clear, the test above should expect a type error; it's a problem if we don't get one.

The code looks great, though!  Next step: formal specification?  I'm not physically present to help with that one, but we can video chat and see how I can help.

I'm good for merging this if everyone else is.  I'm not pushing the button because I'm the remote party and I don't want to interfere with anything.

**Comment by maz** [comment]
@zepalmer I just added some tests to cover those cases (except for the looping. I want to wait until we at least get arrays in littlebang or bigbang so that it won't be so hard to write). I'd be fine with meeting to talk formal specification at some point (possibly tomorrow).

**Comment by zepalmer** [comment]
Excellent!  Send me an e-mail to coordinate a time; my day is filling up crazily fast and GitHub isn't usually where one handles scheduling.  :)

Thanks for the great work!

**Pull request merged**
